Test env variables 14

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -22,6 +22,41 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+
+    - name: Check for Secret availability
+      id: secret-check
+      # perform secret check & put boolean result as an output
+      shell: bash
+      run: |
+        if [ "${{ secrets.SECRET }}" != '' ]; then
+          echo "available=true" >> $GITHUB_OUTPUT;
+        else
+          echo "available=false" >> $GITHUB_OUTPUT;
+        fi
+
+    - name: Check Inadequate Permissions
+      if: ${{ steps.secret-check.outputs.available != 'true' }}
+      # provide feedback for likely problem, note dependabot cannot access
+      # secrets by default. Secondly, this step forces job failure due to
+      # missing secret via `exit 1`
+      shell: bash
+      run: |
+        if [ "${{ github.actor }}" == "dependabot[bot]" ]; then
+          echo >&2 "Unable to access secrets as unprivileged dependabot.";
+        else
+          echo >&2 "Inadequate Permissions or missing secret value";
+        fi
+        exit 1
+
+    - name: Execute Step requiring secret
+      # If you didn't abort step above, then use this conditional
+      # if: ${{ steps.secret-check.outputs.available == 'true' }}
+      shell: bash
+      # Key will be blocked out in log output but will be not empty
+      run: |
+        echo "This command is executed with non-empty key: \
+          ${{ secrets.SECRET }}"
+
     - uses: actions/checkout@v3
 
     - name: Start docker containers
